import logger from '../../shared/utils/logger.js';
import { query, getClient } from '../../db/connection.js';

const TABLES = ['users', 'properties', 'units', 'leases', 'categories', 'tickets', 'ticket_status_history', 'technicians', 'availability_slots', 'materials', 'notifications', 'documents', 'ratings', 'inference_logs', 'system_settings', 'sla_config', 'ai_threshold_config', 'audit_logs', 'security_audit_logs', 'messages', 'ticket_comments', 'job_evidence', 'completion_reports'];

/* Insert order respects foreign keys: users -> categories/properties ->
   units/technicians -> leases/tickets -> children -> config/logs. */
const RESTORE_ORDER = ['users', 'categories', 'properties', 'units', 'technicians', 'leases', 'tickets', 'ticket_status_history', 'ticket_comments', 'availability_slots', 'materials', 'job_evidence', 'completion_reports', 'notifications', 'documents', 'ratings', 'messages', 'inference_logs', 'system_settings', 'sla_config', 'ai_threshold_config', 'audit_logs', 'security_audit_logs'];

const tableExists = async (table) => {
  const res = await query(
    `SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = $1`,
    [table]
  );
  return res.rowCount > 0;
};

/* Real database backup: dumps every known table to JSON. */
const exportData = async () => {
  const data = { app: 'SPMT', version: 1, exportedAt: new Date().toISOString(), tables: {} };
  const counts = {};
  const skipped = [];
  for (const table of TABLES) {
    try {
      if (!(await tableExists(table))) { skipped.push(table); continue; }
      const result = await query(`SELECT * FROM ${table}`);
      data.tables[table] = result.rows;
      counts[table] = result.rows.length;
    } catch (err) {
      logger.error(`Backup export failed for table ${table}: ${err.message}`);
      skipped.push(table);
    }
  }
  // Backwards compatibility: also expose tables at top level
  const legacy = { app: data.app, version: data.version, exportedAt: data.exportedAt, ...data.tables };
  logger.info(`Database export completed: ${Object.values(counts).reduce((a, b) => a + b, 0)} records`);
  return { success: true, data: legacy, backup: data, meta: { counts, skipped, exportedAt: data.exportedAt }, message: 'Export completed' };
};

const SQL_MARKER = '-- SPMT database backup (generated by SPMT backup service)';

/* Render a JS value as a Postgres literal for the .sql dump. */
const toSqlLiteral = (v) => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  if (typeof v === 'boolean') return v ? 'TRUE' : 'FALSE';
  if (v instanceof Date) return `'${v.toISOString().replace(/'/g, "''")}'`;
  if (Buffer.isBuffer(v)) return `'\\x${v.toString('hex')}'`;
  if (Array.isArray(v)) {
    if (v.length === 0) return `'{}'`;
    const els = v.map(e => (e === null || e === undefined
      ? 'NULL'
      : `"${String(e).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`));
    return `'{${els.join(',')}}'`;
  }
  if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const ident = (name) => `"${String(name).replace(/"/g, '')}"`;

/* Native-style Postgres dump: TRUNCATE + INSERTs + sequence resync,
   runnable with psql or via Restore from file. */
const exportSql = async () => {
  const exportedAt = new Date().toISOString();
  const dumped = [];
  const counts = {};
  for (const table of TABLES) {
    try {
      if (!(await tableExists(table))) continue;
      const countRes = await query(`SELECT COUNT(*)::int AS count FROM ${table}`);
      dumped.push(table);
      counts[table] = countRes.rows[0].count;
    } catch (err) {
      logger.error(`Backup SQL export failed for table ${table}: ${err.message}`);
    }
  }
  // Re-read rows in FK-safe order (keeps memory to one table at a time)
  const lines = [
    SQL_MARKER,
    `-- exportedAt: ${exportedAt}`,
    `-- app: SPMT v1`,
    '',
    'BEGIN;',
    '',
  ];
  if (dumped.length) lines.push(`TRUNCATE TABLE ${dumped.join(', ')} RESTART IDENTITY CASCADE;`, '');
  let totalRows = 0;
  for (const table of RESTORE_ORDER) {
    if (!dumped.includes(table)) continue;
    const result = await query(`SELECT * FROM ${table} ORDER BY 1`);
    for (const row of result.rows) {
      const keys = Object.keys(row);
      if (!keys.length) continue;
      lines.push(`INSERT INTO ${ident(table)} (${keys.map(ident).join(', ')}) VALUES (${keys.map(k => toSqlLiteral(row[k])).join(', ')});`);
      totalRows++;
    }
    if (result.rows.length) lines.push('');
  }
  lines.push('-- Resequence SERIAL primary keys past restored max(id)');
  try {
    const seqRes = await query(
      `SELECT table_name FROM information_schema.columns WHERE table_schema = 'public' AND column_name = 'id' AND data_type = 'integer'`
    );
    for (const r of seqRes.rows) {
      const t = r.table_name.replace(/'/g, "''");
      lines.push(`DO $$ BEGIN PERFORM setval(pg_get_serial_sequence('public.${t}', 'id'), COALESCE((SELECT MAX(id) FROM public.${ident(r.table_name)}), 0) + 1, false); EXCEPTION WHEN OTHERS THEN NULL; END $$;`);
    }
  } catch { /* ignore */ }
  lines.push('', 'COMMIT;', '');
  const sql = lines.join('\n');
  const stamp = exportedAt.replace(/[:.]/g, '-').slice(0, 19);
  logger.info(`Database SQL export completed: ${totalRows} records`);
  return {
    success: true,
    data: { format: 'sql', filename: `spmt-backup-${stamp}.sql`, sql, exportedAt },
    meta: { counts, exportedAt, totalRows },
    message: 'SQL export completed',
  };
};

/* Execute a previously generated .sql backup (must carry our marker). */
const importSql = async (sqlText) => {
  const AppError = (await import('../../shared/errors/AppError.js')).default;
  if (typeof sqlText !== 'string' || !sqlText.startsWith(SQL_MARKER)) {
    throw AppError.badRequest('Invalid SQL backup file: SPMT marker not found');
  }
  if (sqlText.length > 50 * 1024 * 1024) throw AppError.badRequest('SQL backup too large (max 50 MB)');
  const client = await getClient();
  try {
    await client.query(sqlText);
  } catch (err) {
    throw AppError.badRequest(`SQL restore failed: ${err.message}`);
  } finally {
    client.release();
  }
  logger.info('Database SQL restore completed');
  return { success: true, message: 'Restore complete. Database replaced with SQL backup.' };
};

const getInfo = async () => {
  const counts = {};
  for (const table of TABLES) {
    try {
      if (!(await tableExists(table))) continue;
      const res = await query(`SELECT COUNT(*)::int AS count FROM ${table}`);
      counts[table] = res.rows[0].count;
    } catch { /* ignore per-table errors */ }
  }
  let dbSize = null;
  try {
    const res = await query(`SELECT pg_size_pretty(pg_database_size(current_database())) AS size`);
    dbSize = res.rows[0]?.size || null;
  } catch { /* ignore */ }
  const totalRows = Object.values(counts).reduce((a, b) => a + b, 0);
  return { success: true, data: { counts, totalRows, tableCount: Object.keys(counts).length, dbSize }, message: 'Backup info retrieved' };
};

/* Accept the shapes produced by exportData (current + legacy + bare-tables). */
const unwrapPayload = (payload) => {
  if (!payload || typeof payload !== 'object') return null;
  const src = payload.tables && typeof payload.tables === 'object' ? payload.tables
    : payload.data && typeof payload.data === 'object' && !Array.isArray(payload.data) ? unwrapPayload(payload.data)
    : payload;
  if (!src || typeof src !== 'object') return null;
  const tables = {};
  for (const t of TABLES) {
    if (Array.isArray(src[t])) tables[t] = src[t];
  }
  return tables;
};

const toDbValue = (v) => {
  if (v === undefined) return null;
  if (v !== null && typeof v === 'object' && !(v instanceof Date) && !Buffer.isBuffer(v)) return JSON.stringify(v);
  return v;
};

const resyncSerialSequences = async (client) => {
  // Point SERIAL sequences past restored max(id) so future inserts don't clash.
  const res = await client.query(
    `SELECT table_name, column_name FROM information_schema.columns
     WHERE table_schema = 'public' AND column_name = 'id' AND data_type = 'integer'`
  );
  for (const row of res.rows) {
    try {
      await client.query(
        `SELECT setval(pg_get_serial_sequence($1, 'id'), COALESCE((SELECT MAX(id) FROM ${row.table_name}), 0) + 1, false)`,
        [`public.${row.table_name}`]
      );
    } catch { /* table without a sequence (e.g. UUID pk) — ignore */ }
  }
};

/* True restore: wipes tables and re-inserts the backup rows with their
   original ids inside a single transaction (FK-safe order). */
const replaceRestore = async (tables) => {
  const client = await getClient();
  let restored = 0;
  try {
    await client.query('BEGIN');
    const existing = [];
    for (const t of RESTORE_ORDER) {
      const exists = (await client.query(
        `SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = $1`, [t]
      )).rowCount > 0;
      if (exists) existing.push(t);
    }
    if (existing.length) {
      await client.query(`TRUNCATE TABLE ${existing.join(', ')} RESTART IDENTITY CASCADE`);
    }
    for (const table of RESTORE_ORDER) {
      const rows = tables[table];
      if (!Array.isArray(rows) || rows.length === 0) continue;
      for (const row of rows) {
        const keys = Object.keys(row);
        if (!keys.length) continue;
        const cols = keys.map(k => `"${k.replace(/"/g, '')}"`).join(', ');
        const vals = keys.map((_, i) => `$${i + 1}`).join(', ');
        const values = keys.map(k => toDbValue(row[k]));
        await client.query(`INSERT INTO ${table} (${cols}) VALUES (${vals})`, values);
        restored++;
      }
    }
    await resyncSerialSequences(client);
    await client.query('COMMIT');
  } catch (err) {
    try { await client.query('ROLLBACK'); } catch { /* ignore */ }
    throw err;
  } finally {
    client.release();
  }
  return restored;
};

/* Non-destructive merge: inserts rows that don't conflict, keeps current data. */
const mergeRestore = async (tables) => {
  let imported = 0;
  for (const table of RESTORE_ORDER) {
    const rows = tables[table];
    if (!Array.isArray(rows) || rows.length === 0) continue;
    if (!(await tableExists(table))) continue;
    for (const row of rows) {
      const keys = Object.keys(row).filter(k => k !== 'created_at');
      if (!keys.length) continue;
      const cols = keys.map(k => `"${k.replace(/"/g, '')}"`).join(', ');
      const vals = keys.map((_, i) => `$${i + 1}`).join(', ');
      const values = keys.map(k => toDbValue(row[k]));
      await query(`INSERT INTO ${table} (${cols}) VALUES (${vals}) ON CONFLICT DO NOTHING`, values);
      imported++;
    }
  }
  return imported;
};

const importData = async (importPayload, options = {}) => {
  // SQL script restore: { sql: '...' }
  if (importPayload && typeof importPayload.sql === 'string') {
    return importSql(importPayload.sql);
  }
  const resolved = unwrapPayload(importPayload);
  if (!resolved || Object.keys(resolved).length === 0) {
    const AppError = (await import('../../shared/errors/AppError.js')).default;
    throw AppError.badRequest('Invalid backup file: no recognisable table data found');
  }
  const mode = options.mode === 'merge' ? 'merge' : 'replace';
  const count = mode === 'merge' ? await mergeRestore(resolved) : await replaceRestore(resolved);
  logger.info(`Database ${mode} restore completed: ${count} records`);
  return {
    success: true,
    message: mode === 'merge'
      ? `Merge complete. ${count} records processed (existing data kept).`
      : `Restore complete. ${count} records restored (database replaced with backup).`,
  };
};

export { exportData, exportSql, importData, importSql, getInfo };
