version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: spmt-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: spmt
      POSTGRES_USER: spmt_user
      POSTGRES_PASSWORD: spmt_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
