const ALL_PERMISSIONS = [
  { id: 'tickets.create', label: 'Create Ticket', group: 'tickets' },
  { id: 'tickets.view.own', label: 'View Own Tickets', group: 'tickets' },
  { id: 'tickets.view.all', label: 'View All Tickets', group: 'tickets' },
  { id: 'tickets.update.status', label: 'Update Ticket Status', group: 'tickets' },
  { id: 'tickets.override.category', label: 'Override AI Category', group: 'tickets' },
  { id: 'tickets.assign', label: 'Assign Tickets', group: 'tickets' },
  { id: 'tickets.escalate', label: 'Escalate Tickets', group: 'tickets' },
  { id: 'tickets.reopen', label: 'Reopen Tickets', group: 'tickets' },
  { id: 'tickets.delete', label: 'Delete Tickets', group: 'tickets' },
  { id: 'tickets.close', label: 'Close Tickets', group: 'tickets' },
  { id: 'tickets.approve', label: 'Approve Ticket Work', group: 'tickets' },
  { id: 'tickets.reject', label: 'Reject Ticket Work', group: 'tickets' },
  { id: 'tickets.export', label: 'Export Tickets', group: 'tickets' },
  { id: 'properties.view.own', label: 'View Own Properties', group: 'properties' },
  { id: 'properties.view.all', label: 'View All Properties', group: 'properties' },
  { id: 'properties.manage', label: 'Manage Properties', group: 'properties' },
  { id: 'units.view.own', label: 'View Own Units', group: 'units' },
  { id: 'units.view.all', label: 'View All Units', group: 'units' },
  { id: 'units.manage', label: 'Manage Units', group: 'units' },
  { id: 'users.view', label: 'View Users', group: 'users' },
  { id: 'users.manage', label: 'Manage Users', group: 'users' },
  { id: 'users.change.role', label: 'Change User Roles', group: 'users' },
  { id: 'users.approve', label: 'Approve Users', group: 'users' },
  { id: 'categories.view', label: 'View Categories', group: 'categories' },
  { id: 'categories.manage', label: 'Manage Categories', group: 'categories' },
  { id: 'categories.ai.thresholds', label: 'Edit AI Thresholds', group: 'categories' },
  { id: 'reports.view', label: 'View Reports', group: 'reports' },
  { id: 'reports.export', label: 'Export Reports', group: 'reports' },
  { id: 'analytics.view', label: 'View Analytics', group: 'analytics' },
  { id: 'activity.view', label: 'View Activity Feed', group: 'activity' },
  { id: 'notifications.view', label: 'View Notifications', group: 'notifications' },
  { id: 'notifications.retry', label: 'Retry / Dismiss Notifications', group: 'notifications' },
  { id: 'messages.templates', label: 'View Notification Templates', group: 'notifications' },
  { id: 'messages.send', label: 'Send Messages', group: 'notifications' },
  { id: 'settings.view', label: 'View System Settings', group: 'settings' },
  { id: 'settings.manage', label: 'Edit System Settings', group: 'settings' },
  { id: 'backup.view', label: 'View Backup Snapshots', group: 'backup' },
  { id: 'backup.trigger', label: 'Trigger Backup', group: 'backup' },
  { id: 'backup.restore', label: 'Restore from Backup', group: 'backup' },
  { id: 'audit.view', label: 'View Audit Trail', group: 'audit' },
  { id: 'logs.view', label: 'View System Logs', group: 'audit' },
  { id: 'technicians.manage', label: 'Manage Technicians', group: 'technicians' },
  { id: 'technicians.view', label: 'View Technicians', group: 'technicians' },
  { id: 'comments.create', label: 'Add Comments', group: 'comments' },
  { id: 'comments.delete', label: 'Delete Comments', group: 'comments' },
  { id: 'profile.read', label: 'Read Own Profile', group: 'profile' },
  { id: 'profile.write', label: 'Update Own Profile', group: 'profile' },
  { id: 'roles.view', label: 'View Role Definitions', group: 'roles' },
  { id: 'roles.manage', label: 'Manage Role Definitions', group: 'roles' },
  { id: 'permissions.view', label: 'View Permissions Matrix', group: 'permissions' },
  { id: 'permissions.manage', label: 'Edit Permissions Matrix', group: 'permissions' },
];

const RBAC_MATRIX = {
  SYSTEM_ADMIN: ALL_PERMISSIONS.map(p => p.id),

  PROPERTY_MANAGER: [
    'tickets.create', 'tickets.view.own', 'tickets.view.all', 'tickets.update.status',
    'tickets.assign', 'tickets.escalate', 'tickets.reopen', 'tickets.close',
    'tickets.approve', 'tickets.reject', 'tickets.export',
    'properties.view.own', 'properties.view.all', 'properties.manage',
    'units.view.own', 'units.view.all', 'units.manage',
    'users.view',
    'categories.view',
    'reports.view', 'reports.export',
    'analytics.view',
    'activity.view',
    'notifications.view', 'notifications.retry',
    'technicians.view',
    'comments.create',
    'profile.read', 'profile.write',
    'audit.view',
  ],

  SERVICE_PROVIDER: [
    'tickets.view.own', 'tickets.update.status',
    'properties.view.own',
    'comments.create',
    'profile.read', 'profile.write',
  ],

  ADMIN: [
    'tickets.create', 'tickets.view.own', 'tickets.view.all', 'tickets.update.status',
    'tickets.override.category', 'tickets.assign', 'tickets.escalate', 'tickets.reopen',
    'tickets.delete', 'tickets.close', 'tickets.approve', 'tickets.reject', 'tickets.export',
    'properties.view.own', 'properties.view.all', 'properties.manage',
    'units.view.own', 'units.view.all', 'units.manage',
    'users.view', 'users.manage',
    'categories.view', 'categories.manage',
    'reports.view', 'reports.export',
    'analytics.view',
    'activity.view',
    'notifications.view', 'notifications.retry',
    'settings.view',
    'technicians.view',
    'comments.create', 'comments.delete',
    'profile.read', 'profile.write',
    'audit.view',
    'roles.view',
    'permissions.view',
  ],

  TENANT: [
    'tickets.create', 'tickets.view.own', 'tickets.update.status',
    'properties.view.own',
    'units.view.own',
    'comments.create',
    'profile.read', 'profile.write',
  ],

  GUEST: [
    'tickets.view.own',
    'profile.read',
  ],
};

const PERMISSION_GROUPS = [
  { id: 'tickets', label: 'Tickets' },
  { id: 'properties', label: 'Properties' },
  { id: 'units', label: 'Units' },
  { id: 'users', label: 'Users' },
  { id: 'categories', label: 'Categories' },
  { id: 'reports', label: 'Reports & Analytics' },
  { id: 'analytics', label: 'Analytics' },
  { id: 'activity', label: 'Activity' },
  { id: 'notifications', label: 'Notifications' },
  { id: 'settings', label: 'Settings' },
  { id: 'backup', label: 'Backup' },
  { id: 'audit', label: 'Audit & Logs' },
  { id: 'technicians', label: 'Technicians' },
  { id: 'comments', label: 'Comments' },
  { id: 'profile', label: 'Profile' },
  { id: 'roles', label: 'Roles' },
  { id: 'permissions', label: 'Permissions' },
];

export { ALL_PERMISSIONS, PERMISSION_GROUPS, RBAC_MATRIX };
