"""Generate a synthetic labelled dataset for training the category classifier.

Each ticket is a short (title + description) string mapped to one of the
SPMT maintenance categories. Data is random but seeded so results are
reproducible across runs.
"""

import random
import csv
from pathlib import Path

CATEGORIES = [
    "Plumbing",
    "Electrical",
    "HVAC",
    "Appliances",
    "Structural",
    "Security",
    "Landscaping",
    "Pest Control",
]

# Keywords heavily weighted for each category. Real-world sentences are
# generated by mixing category-specific tokens with generic filler.
KEYWORD_POOL = {
    "Plumbing": ["leak", "pipe", "drain", "toilet", "sink", "faucet", "water running", "clogged", "sewer", "tap dripping", "shower", "overflow", "burst pipe", "low water pressure"],
    "Electrical": ["power outage", "not working outlet", "flickering light", "breaker tripped", "spark", "wiring", "shorted", "switch broken", "socket", "no electricity", "circuit", "fuse blown"],
    "HVAC": ["air conditioner", "heating", "no heat", "no cold air", "thermostat", "furnace", "vent coming", "fan not spinning", "cooling", "aircon not cooling", "hvac", "aircon leaking"],
    "Appliances": ["fridge not cooling", "refrigerator", "dishwasher", "washing machine", "dryer", "stove", "oven", "microwave not heating", "freezer", "appliance broken", "washing machine leaking"],
    "Structural": ["crack in wall", "ceiling stain", "roof leak", "broken window", "door stuck", "hole in floor", "foundation", "water stain", "damaged drywall", "mold", "broken frame", "rotten board"],
    "Security": ["lock broken", "alarm going off", "camera not working", "doorbell", "broken key", "intrusion", "keypad", "intercom not working", "faulty lock", "security gate"],
    "Landscaping": ["garden overgrown", "lawn mowing", "broken fence", "tree branch", "grass", "sprinkler", "yard", "weeds", "gate stuck", "patio dirty", "irrigation not working"],
    "Pest Control": ["termites", "rat", "mouse", "cockroach", "ants", "infestation", "bed bugs", "wasps", "spider", "roaches", "rodent"],
}

GENERIC_FILLER = [
    "there is an issue", "please help", "needs fixing", "urgent attention",
    "has been like this", "reported by tenant", "cannot use it", "please send someone",
    "we need assistance", "this has been ongoing", "repair needed",
]

PHRASE_OPENERS = [
    "The {kw} in the {room} is {state}.",
    "We have a problem with the {kw} at {room}.",
    "Please attend to the {kw}.",
    "Tenant reports {kw} at {room}.",
    "There is an issue with the {kw}.",
    "Unable to use the {kw} at {room}.",
    "Complaint: the {kw} needs attention.",
    "The {kw} has been {state} for a while.",
    "Need urgent help with the {kw}.",
    "Noticed that the {kw} at {room} requires repair.",
]

ROOMS = ["kitchen", "bathroom", "bedroom", "living room", "garage", "hallway", "balcony", "laundry room", "lobby", "store room"]
STATES = ["broken", "leaking", "malfunctioning", "not working", "damaged", "faulty", "out of order", "stuck", "failing", "damaged"]


def _make_description(keyword: str) -> str:
    template = random.choice(PHRASE_OPENERS)
    return template.format(kw=keyword, room=random.choice(ROOMS), state=random.choice(STATES))


def generate_dataset(n_per_category: int = 120, seed: int = 42) -> list[dict]:
    """Return list of {text, category} labelled samples."""
    rng = random.Random(seed)
    rows = []
    for category, pool in KEYWORD_POOL.items():
        # duplicate the pool so we can sample with replacement enough times
        expanded = pool * (n_per_category // len(pool) + 1)
        for i in range(n_per_category):
            keyword = rng.choice(expanded)
            desc = _make_description(keyword)
            # occasionally append an unrelated filler to make it noise-robust
            if rng.random() < 0.25:
                desc = f"{desc} {rng.choice(GENERIC_FILLER)}."
            rows.append({"text": f"{category} issue: {desc}", "category": category})
    rng.shuffle(rows)
    return rows


def write_dataset(path: Path, n_per_category: int = 120, seed: int = 42) -> list[dict]:
    rows = generate_dataset(n_per_category, seed)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["text", "category"])
        writer.writeheader()
        writer.writerows(rows)
    return rows


if __name__ == "__main__":
    out = Path(__file__).resolve().parents[1] / "data" / "tickets_dataset.csv"
    rows = write_dataset(out)
    print(f"Wrote {len(rows)} labelled samples to {out}")
